<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'iso_code' => 'AF', 'phone_code' => '+93', 'flag' => '🇦🇫'],
            ['name' => 'Albania', 'iso_code' => 'AL', 'phone_code' => '+355', 'flag' => '🇦🇱'],
            ['name' => 'Algeria', 'iso_code' => 'DZ', 'phone_code' => '+213', 'flag' => '🇩🇿'],
            ['name' => 'Andorra', 'iso_code' => 'AD', 'phone_code' => '+376', 'flag' => '🇦🇩'],
            ['name' => 'Angola', 'iso_code' => 'AO', 'phone_code' => '+244', 'flag' => '🇦🇴'],
            ['name' => 'Argentina', 'iso_code' => 'AR', 'phone_code' => '+54', 'flag' => '🇦🇷'],
            ['name' => 'Armenia', 'iso_code' => 'AM', 'phone_code' => '+374', 'flag' => '🇦🇲'],
            ['name' => 'Australia', 'iso_code' => 'AU', 'phone_code' => '+61', 'flag' => '🇦🇺'],
            ['name' => 'Austria', 'iso_code' => 'AT', 'phone_code' => '+43', 'flag' => '🇦🇹'],
            ['name' => 'Azerbaijan', 'iso_code' => 'AZ', 'phone_code' => '+994', 'flag' => '🇦🇿'],
            ['name' => 'Bahrain', 'iso_code' => 'BH', 'phone_code' => '+973', 'flag' => '🇧🇭'],
            ['name' => 'Bangladesh', 'iso_code' => 'BD', 'phone_code' => '+880', 'flag' => '🇧🇩'],
            ['name' => 'Belarus', 'iso_code' => 'BY', 'phone_code' => '+375', 'flag' => '🇧🇾'],
            ['name' => 'Belgium', 'iso_code' => 'BE', 'phone_code' => '+32', 'flag' => '🇧🇪'],
            ['name' => 'Bolivia', 'iso_code' => 'BO', 'phone_code' => '+591', 'flag' => '🇧🇴'],
            ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'BA', 'phone_code' => '+387', 'flag' => '🇧🇦'],
            ['name' => 'Brazil', 'iso_code' => 'BR', 'phone_code' => '+55', 'flag' => '🇧🇷'],
            ['name' => 'Bulgaria', 'iso_code' => 'BG', 'phone_code' => '+359', 'flag' => '🇧🇬'],
            ['name' => 'Cambodia', 'iso_code' => 'KH', 'phone_code' => '+855', 'flag' => '🇰🇭'],
            ['name' => 'Cameroon', 'iso_code' => 'CM', 'phone_code' => '+237', 'flag' => '🇨🇲'],
            ['name' => 'Canada', 'iso_code' => 'CA', 'phone_code' => '+1', 'flag' => '🇨🇦'],
            ['name' => 'Chile', 'iso_code' => 'CL', 'phone_code' => '+56', 'flag' => '🇨🇱'],
            ['name' => 'China', 'iso_code' => 'CN', 'phone_code' => '+86', 'flag' => '🇨🇳'],
            ['name' => 'Colombia', 'iso_code' => 'CO', 'phone_code' => '+57', 'flag' => '🇨🇴'],
            ['name' => 'Costa Rica', 'iso_code' => 'CR', 'phone_code' => '+506', 'flag' => '🇨🇷'],
            ['name' => 'Croatia', 'iso_code' => 'HR', 'phone_code' => '+385', 'flag' => '🇭🇷'],
            ['name' => 'Cuba', 'iso_code' => 'CU', 'phone_code' => '+53', 'flag' => '🇨🇺'],
            ['name' => 'Cyprus', 'iso_code' => 'CY', 'phone_code' => '+357', 'flag' => '🇨🇾'],
            ['name' => 'Czech Republic', 'iso_code' => 'CZ', 'phone_code' => '+420', 'flag' => '🇨🇿'],
            ['name' => 'Denmark', 'iso_code' => 'DK', 'phone_code' => '+45', 'flag' => '🇩🇰'],
            ['name' => 'Dominican Republic', 'iso_code' => 'DO', 'phone_code' => '+1', 'flag' => '🇩🇴'],
            ['name' => 'Ecuador', 'iso_code' => 'EC', 'phone_code' => '+593', 'flag' => '🇪🇨'],
            ['name' => 'Egypt', 'iso_code' => 'EG', 'phone_code' => '+20', 'flag' => '🇪🇬'],
            ['name' => 'El Salvador', 'iso_code' => 'SV', 'phone_code' => '+503', 'flag' => '🇸🇻'],
            ['name' => 'Estonia', 'iso_code' => 'EE', 'phone_code' => '+372', 'flag' => '🇪🇪'],
            ['name' => 'Ethiopia', 'iso_code' => 'ET', 'phone_code' => '+251', 'flag' => '🇪🇹'],
            ['name' => 'Finland', 'iso_code' => 'FI', 'phone_code' => '+358', 'flag' => '🇫🇮'],
            ['name' => 'France', 'iso_code' => 'FR', 'phone_code' => '+33', 'flag' => '🇫🇷'],
            ['name' => 'Georgia', 'iso_code' => 'GE', 'phone_code' => '+995', 'flag' => '🇬🇪'],
            ['name' => 'Germany', 'iso_code' => 'DE', 'phone_code' => '+49', 'flag' => '🇩🇪'],
            ['name' => 'Ghana', 'iso_code' => 'GH', 'phone_code' => '+233', 'flag' => '🇬🇭'],
            ['name' => 'Greece', 'iso_code' => 'GR', 'phone_code' => '+30', 'flag' => '🇬🇷'],
            ['name' => 'Guatemala', 'iso_code' => 'GT', 'phone_code' => '+502', 'flag' => '🇬🇹'],
            ['name' => 'Honduras', 'iso_code' => 'HN', 'phone_code' => '+504', 'flag' => '🇭🇳'],
            ['name' => 'Hong Kong', 'iso_code' => 'HK', 'phone_code' => '+852', 'flag' => '🇭🇰'],
            ['name' => 'Hungary', 'iso_code' => 'HU', 'phone_code' => '+36', 'flag' => '🇭🇺'],
            ['name' => 'Iceland', 'iso_code' => 'IS', 'phone_code' => '+354', 'flag' => '🇮🇸'],
            ['name' => 'India', 'iso_code' => 'IN', 'phone_code' => '+91', 'flag' => '🇮🇳'],
            ['name' => 'Indonesia', 'iso_code' => 'ID', 'phone_code' => '+62', 'flag' => '🇮🇩'],
            ['name' => 'Iran', 'iso_code' => 'IR', 'phone_code' => '+98', 'flag' => '🇮🇷'],
            ['name' => 'Iraq', 'iso_code' => 'IQ', 'phone_code' => '+964', 'flag' => '🇮🇶'],
            ['name' => 'Ireland', 'iso_code' => 'IE', 'phone_code' => '+353', 'flag' => '🇮🇪'],
            ['name' => 'Israel', 'iso_code' => 'IL', 'phone_code' => '+972', 'flag' => '🇮🇱'],
            ['name' => 'Italy', 'iso_code' => 'IT', 'phone_code' => '+39', 'flag' => '🇮🇹'],
            ['name' => 'Jamaica', 'iso_code' => 'JM', 'phone_code' => '+1', 'flag' => '🇯🇲'],
            ['name' => 'Japan', 'iso_code' => 'JP', 'phone_code' => '+81', 'flag' => '🇯🇵'],
            ['name' => 'Jordan', 'iso_code' => 'JO', 'phone_code' => '+962', 'flag' => '🇯🇴'],
            ['name' => 'Kazakhstan', 'iso_code' => 'KZ', 'phone_code' => '+7', 'flag' => '🇰🇿'],
            ['name' => 'Kenya', 'iso_code' => 'KE', 'phone_code' => '+254', 'flag' => '🇰🇪'],
            ['name' => 'Kuwait', 'iso_code' => 'KW', 'phone_code' => '+965', 'flag' => '🇰🇼'],
            ['name' => 'Latvia', 'iso_code' => 'LV', 'phone_code' => '+371', 'flag' => '🇱🇻'],
            ['name' => 'Lebanon', 'iso_code' => 'LB', 'phone_code' => '+961', 'flag' => '🇱🇧'],
            ['name' => 'Libya', 'iso_code' => 'LY', 'phone_code' => '+218', 'flag' => '🇱🇾'],
            ['name' => 'Lithuania', 'iso_code' => 'LT', 'phone_code' => '+370', 'flag' => '🇱🇹'],
            ['name' => 'Luxembourg', 'iso_code' => 'LU', 'phone_code' => '+352', 'flag' => '🇱🇺'],
            ['name' => 'Malaysia', 'iso_code' => 'MY', 'phone_code' => '+60', 'flag' => '🇲🇾'],
            ['name' => 'Mexico', 'iso_code' => 'MX', 'phone_code' => '+52', 'flag' => '🇲🇽'],
            ['name' => 'Morocco', 'iso_code' => 'MA', 'phone_code' => '+212', 'flag' => '🇲🇦'],
            ['name' => 'Netherlands', 'iso_code' => 'NL', 'phone_code' => '+31', 'flag' => '🇳🇱'],
            ['name' => 'New Zealand', 'iso_code' => 'NZ', 'phone_code' => '+64', 'flag' => '🇳🇿'],
            ['name' => 'Nigeria', 'iso_code' => 'NG', 'phone_code' => '+234', 'flag' => '🇳🇬'],
            ['name' => 'Norway', 'iso_code' => 'NO', 'phone_code' => '+47', 'flag' => '🇳🇴'],
            ['name' => 'Oman', 'iso_code' => 'OM', 'phone_code' => '+968', 'flag' => '🇴🇲'],
            ['name' => 'Pakistan', 'iso_code' => 'PK', 'phone_code' => '+92', 'flag' => '🇵🇰'],
            ['name' => 'Palestine', 'iso_code' => 'PS', 'phone_code' => '+970', 'flag' => '🇵🇸'],
            ['name' => 'Peru', 'iso_code' => 'PE', 'phone_code' => '+51', 'flag' => '🇵🇪'],
            ['name' => 'Philippines', 'iso_code' => 'PH', 'phone_code' => '+63', 'flag' => '🇵🇭'],
            ['name' => 'Poland', 'iso_code' => 'PL', 'phone_code' => '+48', 'flag' => '🇵🇱'],
            ['name' => 'Portugal', 'iso_code' => 'PT', 'phone_code' => '+351', 'flag' => '🇵🇹'],
            ['name' => 'Qatar', 'iso_code' => 'QA', 'phone_code' => '+974', 'flag' => '🇶🇦'],
            ['name' => 'Romania', 'iso_code' => 'RO', 'phone_code' => '+40', 'flag' => '🇷🇴'],
            ['name' => 'Russia', 'iso_code' => 'RU', 'phone_code' => '+7', 'flag' => '🇷🇺'],
            ['name' => 'Saudi Arabia', 'iso_code' => 'SA', 'phone_code' => '+966', 'flag' => '🇸🇦'],
            ['name' => 'Serbia', 'iso_code' => 'RS', 'phone_code' => '+381', 'flag' => '🇷🇸'],
            ['name' => 'Singapore', 'iso_code' => 'SG', 'phone_code' => '+65', 'flag' => '🇸🇬'],
            ['name' => 'Slovakia', 'iso_code' => 'SK', 'phone_code' => '+421', 'flag' => '🇸🇰'],
            ['name' => 'Slovenia', 'iso_code' => 'SI', 'phone_code' => '+386', 'flag' => '🇸🇮'],
            ['name' => 'South Africa', 'iso_code' => 'ZA', 'phone_code' => '+27', 'flag' => '🇿🇦'],
            ['name' => 'South Korea', 'iso_code' => 'KR', 'phone_code' => '+82', 'flag' => '🇰🇷'],
            ['name' => 'Spain', 'iso_code' => 'ES', 'phone_code' => '+34', 'flag' => '🇪🇸'],
            ['name' => 'Sudan', 'iso_code' => 'SD', 'phone_code' => '+249', 'flag' => '🇸🇩'],
            ['name' => 'Sweden', 'iso_code' => 'SE', 'phone_code' => '+46', 'flag' => '🇸🇪'],
            ['name' => 'Switzerland', 'iso_code' => 'CH', 'phone_code' => '+41', 'flag' => '🇨🇭'],
            ['name' => 'Syria', 'iso_code' => 'SY', 'phone_code' => '+963', 'flag' => '🇸🇾'],
            ['name' => 'Thailand', 'iso_code' => 'TH', 'phone_code' => '+66', 'flag' => '🇹🇭'],
            ['name' => 'Tunisia', 'iso_code' => 'TN', 'phone_code' => '+216', 'flag' => '🇹🇳'],
            ['name' => 'Turkey', 'iso_code' => 'TR', 'phone_code' => '+90', 'flag' => '🇹🇷'],
            ['name' => 'Ukraine', 'iso_code' => 'UA', 'phone_code' => '+380', 'flag' => '🇺🇦'],
            ['name' => 'United Arab Emirates', 'iso_code' => 'AE', 'phone_code' => '+971', 'flag' => '🇦🇪'],
            ['name' => 'United Kingdom', 'iso_code' => 'GB', 'phone_code' => '+44', 'flag' => '🇬🇧'],
            ['name' => 'United States', 'iso_code' => 'US', 'phone_code' => '+1', 'flag' => '🇺🇸'],
            ['name' => 'Venezuela', 'iso_code' => 'VE', 'phone_code' => '+58', 'flag' => '🇻🇪'],
            ['name' => 'Vietnam', 'iso_code' => 'VN', 'phone_code' => '+84', 'flag' => '🇻🇳'],
            ['name' => 'Yemen', 'iso_code' => 'YE', 'phone_code' => '+967', 'flag' => '🇾🇪'],
            ['name' => 'Zambia', 'iso_code' => 'ZM', 'phone_code' => '+260', 'flag' => '🇿🇲'],
            ['name' => 'Zimbabwe', 'iso_code' => 'ZW', 'phone_code' => '+263', 'flag' => '🇿🇼'],
        ];

        DB::table('countries')->insert($countries);
    }
}
